<?php
$productCollection = $this->getData('collection');
$count = $productCollection ? $productCollection->count() : 0;
$carousel = $this->getData('carousel');
$row = $this->getData('row');
$column = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper = Mage::helper('catalog/image');
$theme = $this->helper('puro');
$helpImg = $this->helper('puro/image');
$imgWidth = $theme->getCfg('category/image_width') ? $theme->getCfg('category/image_width') : 270;
$imgHeight = $theme->getCfg('category/image_height') ? $theme->getCfg('category/image_height') : 360;
if ($theme->getCfg('category/aspect_ratio')) {
    $imgHeight = 0;
}
$enable_quickview = Mage::getStoreConfig('ajaxproducts/config/enable_quickview');
$cfdpcart_grid = $theme->getCfg('category_grid/display_addtocart');
$cfdplink_grid = $theme->getCfg('category_grid/display_addtolinks');
$btnClassCart = ($cfdpcart_grid == 1) ? 'display-onhover' : '';
$btnClassLink = ($cfdplink_grid == 1) ? 'display-onhover' : '';
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <div class="category-products">
        <?php $i = 0;
        foreach ($productCollection as $_product): ?>
            <?php /* @var $_product Mage_Catalog_Model_Product */ ?>
            <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
                <div class="owl-carousel products-grid">
            <?php endif ?>
            <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
        <?php endif ?>
            <?php $i++ ?>
            <li class="item effect-pageLeft">
                <div class="product-action">
                    <!-- // Product Label -->
                    <?php echo $this->helper('puro')->getLabel($_product); ?>
                    <!-- // End Product Label -->
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                        <?php if ($carousel == 1): ?>
                            <img
                                class="lazy img-responsive" <?php echo $helpImg->getImgSources($_product, 'small_image', $imgWidth, null); ?>
                                src="<?php echo $this->getSkinUrl('images/AjaxLoader.gif'); ?>"
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        <?php else: ?>
                            <img
                                class="img-responsive lazy" <?php echo $helpImg->getImgSources($_product, 'small_image', $imgWidth, null); ?>
                                src="<?php echo $this->getSkinUrl('images/AjaxLoader.gif'); ?>"
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        <?php endif ?>
                        <?php if ($theme->getCfg('category/alt_image')): ?>
                            <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
                        <?php endif; ?>
                    </a>

                    <div class="actions">
                        <?php if($enable_quickview):?>
                            <div class="action-list quickview hidden-xs">
                                <div class="quickview-wrapper" onclick="quickview(this);" data-url="<?php echo $this->getUrl('ajaxproducts/index/quickview',array('product_id'=>$_product->getId()));?>">
                                    <i class="fa fa-search-plus"></i>
                                </div>
                            </div>
                        <?php endif;?>
                        <?php if($cfdpcart_grid != 0):?>
                        <!-- // Product Button Add To Cart -->
                        <?php if ($_product->isSaleable()): ?>
                            <div class="action-list addtocart">
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart bootstrap-tooltip" data-toggle="tooltip" data-placement="left" onclick="setLocationCache('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                    <span><span><i class="fa fa-shopping-cart"></i></span></span>
                                </button>
                            </div>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <?php endif; ?>
                        <!-- // End Product Button Add To Cart -->
                        <?php if ($cfdplink_grid != 0): ?>
                        <!-- // Product Button Add To Link -->
                        <div class="action-list">
                            <ul class="add-to-links">
                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                    <li class="first"><a href="<?php echo $_compareUrl ?>" class="link-compare bootstrap-tooltip"  data-toggle="tooltip" data-placement="left" title="<?php echo $this->__('Compare');?>"><i class="fa fa-pie-chart"></i></a></li>
                                <?php endif; ?>
                            </ul>
                        </div>
                        <?php endif; ?>
                        <?php if ($cfdplink_grid != 0): ?>
                        <div class="action-list">
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist bootstrap-tooltip" data-toggle="tooltip" data-placement="left" title="<?php echo $this->__('Wishlist');?>"><i class="fa fa-heart"></i></a></li>
                                <?php endif; ?>
                            </ul>
                        </div>
                        <?php endif; ?>
                        <!-- // End Product Button Add To Link -->
                    </div>
                </div>
                <div class="product-content">
                    <h3 class="product-name">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                            <?php echo $this->escapeHtml($_product->getName()) ?>
                        </a>
                    </h3>
                    <?php if ($_product->getRatingSummary()): ?>
                        <!-- // Product Rating Summary -->
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <!-- // End Product Rating Summary -->
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
            </li>
            <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            </ul>
        <?php endif ?>
            <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
                </div>
            <?php endif ?>
        <?php endforeach ?>
    </div>
<?php endif ?>
