<?php
$productCollection = $this->getData('collection');
$count = $productCollection ? $productCollection->count() : 0;
$carousel = $this->getData('carousel');
$row = $this->getData('row');
$column = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper = Mage::helper('catalog/image');
$theme = $this->helper('puro');
$helpImg = $this->helper('puro/image');
$imgWidth = $theme->getCfg('category/image_width') ? $theme->getCfg('category/image_width') : 263;
$imgHeight = $theme->getCfg('category/image_height') ? $theme->getCfg('category/image_height') : 263;
if ($theme->getCfg('category/aspect_ratio')) {
    $imgHeight = 0;
}
?>
<?php if (!$count): ?>
<?php else: ?>
    <div class="category-products">
        <?php $i = 0;
        foreach ($productCollection as $_product): ?>
            <?php /* @var $_product Mage_Catalog_Model_Product */ ?>
            <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
                <div class="owl-carousel">
            <?php endif ?>
            <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
        <?php endif ?>
            <?php $i++ ?>
            <li class="item">
                <div class="product-action">
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                        <?php if ($carousel == 1): ?>
                            <img
                                class="lazyOwl img-responsive" <?php echo $helpImg->getImgSources($_product, 'small_image', $imgWidth, null); ?>
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        <?php else: ?>
                            <img
                                class="img-responsive lazy" <?php echo $helpImg->getImgSources($_product, 'small_image', $imgWidth, null); ?>
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        <?php endif ?>
                    </a>
                </div>
                <div class="product-content">
                    <h3 class="product-name">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                            <?php echo $this->escapeHtml($_product->getName()) ?>
                        </a>
                    </h3>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <input type="checkbox" class="checkbox related-checkbox"
                           id="related-checkbox<?php echo $_product->getId() ?>" name="related_products[]"
                           value="<?php echo $_product->getId() ?>"/>

                    <div class="product-date" data-date="<?php echo $_product->getData('special_to_date') ?>"></div>
                </div>
            </li>
            <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            </ul>
        <?php endif ?>
            <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
                </div>
            <?php endif ?>
        <?php endforeach ?>
    </div>
<?php endif ?>
