<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="blog-wrapper">
    <?php foreach ($posts as $post): ?>
        <div class="postWrapper">
            <div class="postTitle">
                <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                <div class="postDetails">
                    <?php if ($this->getCommentsEnabled()): ?>
                        <?php echo $post->getCommentCount() ? $post->getCommentCount():'0'; ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" > <?php echo Mage::helper('blog')->__('Comments'); ?></a> |
                    <?php endif; ?>
                    <?php $postCats = $post->getCats(); ?>
                    <?php if (!empty($postCats)): ?>
                        <?php echo Mage::helper('blog')->__('Posted in'); ?>
                        <?php foreach ($postCats as $data): ?>
                            <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <?php echo Mage::helper('blog')->__('Posted'); ?>
                    <?php endif; ?><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
                    <h3><?php echo $post->getCreatedTime(); ?></h3>
                </div>
            </div>
            <div class="postContent"><?php echo $post->getPostContent(); ?></div>
            <a class="btn-button" href="<?php echo $post->getAddress(); ?>"><?php echo $this->__('Read More');?></a>
        </div>
    <?php endforeach; ?>
    <div class="toolbar-bottom">
        <?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
    </div>
</div>
