<?php
/**
 * @copyright    Copyright (C) 2015 IcoTheme.com. All Rights Reserved.
 */
?>
<!-- Category Navigation BOF -->
<div class="block block-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Categories'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul id="categories_nav" class="nav-accordion nav-categories">
            <?php echo $this->renderCategoriesMenuHtml(TRUE, TRUE, 0, 'level-top'); ?>
        </ul>
    </div>
</div>
<!-- Category Navigation EOF -->