<script type="text/javascript">
(function() {
  if (typeof janrain !== "object") window.janrain = {};
  if (typeof janrain.settings !== "object") window.janrain.settings = {};
  <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()):?>
    janrain.settings.tokenUrl = "<?php echo Mage::getUrl('engage/rpx/token_url') ?>";
  <?php else:?>
    janrain.settings.tokenUrl = "<?php echo Mage::getUrl('engage/rpx/token_url_add') ?>";
  <?php endif;?>
  janrain.settings.appId    = "<?php echo Mage::getStoreConfig('engage/vars/appid') ?>";
  janrain.settings.appUrl   = "https://<?php echo Mage::getStoreConfig('engage/vars/realm') ?>";
  janrain.settings.type     = 'embed';
  janrain.settings.format   = 'one row';

  function isReady() {
    janrain.ready = true;
  };

  if(document.addEventListener) {
    document.addEventListener("DOMContentLoaded", isReady, false);
  } else {
    window.attachEvent('onload', isReady);
  }

  var e = document.createElement('script');
  e.type = 'text/javascript';
  e.id = 'janrainAuthWidget';

  if(document.location.protocol === 'https:') {
    e.src = 'https://rpxnow.com/load/<?php echo Mage::helper('engage')->rpxRealmName()?>';
  } else {
    e.src = 'http://widget-cdn.rpxnow.com/load/<?php echo Mage::helper('engage')->rpxRealmName()?>';
  }

  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(e, s);
})();
</script>
