<?php
/**
 * @copyright   Copyright (C)2015 IcoTheme.com. All Rights Reserved.
 */
?>
<?php
$blocks = $this->getBlocks();
$id = $this->getConfig('id');
$scroll = $this->getConfig('scroll');
$title = $this->getConfig('widget_title');
?>
<div class="block-container <?php echo $this->getConfig('classes') ?>" id="<?php echo $id ?>">
    <?php if ($title): ?>
        <h2><?php echo $title ?></h2>
    <?php endif ?>
    <div class="<?php echo $scroll == 1 ? 'owl-carousel ' : '' ?>">
        <?php foreach ($blocks as $block): ?>
            <div class="<?php echo $block['class'] ?>">
                <?php echo $block['content'] ?>
            </div>
        <?php endforeach ?>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery('#<?php echo $id;?> .owl-carousel').owlCarousel(<?php echo $this->getConfig('carousel') ?>);
        });
    </script>
</div>
