<?php
$productCollection = $this->getData('collection');
$count = $productCollection ? $productCollection->count() : 0;
$carousel = $this->getData('carousel');
$row = $this->getData('row');
$column = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper = Mage::helper('catalog/image');
$theme = $this->helper('puro');
$helpImg = $this->helper('puro/image');
$imgWidth = 125;
$imgHeight = 144;
if ($theme->getCfg('category/aspect_ratio')) {
    $imgHeight = 0;
}
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <div class="category-products">
        <?php $i = 0;
        foreach ($productCollection as $_product): ?>
            <?php /* @var $_product Mage_Catalog_Model_Product */ ?>
            <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
                <div class="owl-carousel">
            <?php endif ?>
            <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            <ul class="products-grid <?php if ($i == 0) echo 'first'; else if ($i == $count - 1): echo 'last'; endif;
            echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
        <?php endif ?>
            <?php $i++ ?>
            <li class="item">
                <div class="product-action">
                    <div class="product-content">
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                            <?php if ($carousel == 1): ?>
                                <img
                                    class="lazy" <?php echo $helpImg->getImgSources($_product, 'small_image', $imgWidth, null); ?>
                                    src="<?php echo $this->getSkinUrl('images/AjaxLoader.gif'); ?>"
                                    alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            <?php else: ?>
                                <img
                                    class="lazy" <?php echo $helpImg->getImgSources($_product, 'small_image', $imgWidth, null); ?>
                                    src="<?php echo $this->getSkinUrl('images/AjaxLoader.gif'); ?>"
                                    alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            <?php endif ?>
                            <?php if ($theme->getCfg('category/alt_image')): ?>
                                <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
                            <?php endif; ?>
                        </a>

                        <div class="content-wrapper">
                            <h3 class="product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>"
                                   title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                    <?php echo $this->escapeHtml($_product->getName()) ?>
                                </a>
                            </h3>
                            <?php if ($_product->getRatingSummary()): ?>
                                <!-- // Product Rating Summary -->
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                                <!-- // End Product Rating Summary -->
                            <?php endif; ?>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                        </div>
                    </div>
                </div>
            </li>
            <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            </ul>
        <?php endif ?>
            <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
                </div>
            <?php endif ?>
        <?php endforeach ?>
    </div>
<?php endif ?>
