<?php
$_id = $this->getConfig('id');
$_title = $this->getConfig('widget_title');
$_countdown = $this->getConfig('enableCoundown');
$t = microtime();
?>
<div class="col-lg-12">
    <div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $_id ?>">
        <?php if ($_title): ?>
            <h2><?php echo $_title ?></h2>
        <?php endif ?>
        <?php echo $this->renderCollection('collection', $this->getData('mode'), 'icotheme/widgetproducts/collection.phtml') ?>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('#<?php echo $_id;?> .owl-carousel').owlCarousel(<?php echo $this->getConfig('carousel') ?>);
    });
</script>
