<?php
/**
 * @copyright    Copyright (C) 2015 IcoTheme.com. All Rights Reserved.
 */
?>
<!-- navigation BOF -->
<?php
$megaeffect = Mage::getStoreConfig('ultramegamenu/display_options/menuleft_effect');
$_menu = $this->renderCategoriesMenuHtml(FALSE, FALSE, 0, 'level-top', 'sub-wrapper');
$routeName = Mage::app()->getRequest()->getRouteName();
$identifier = Mage::getSingleton('cms/page')->getIdentifier();

?>
<?php if ($_menu): ?>
    <div class="vertical-navigation hidden-xs">
        <div class="vertical-navigation-main">
            <ul class="vertical-navigation-container">
                <?php if (Mage::getStoreConfig('ultramegamenu/display_options/home')) { ?>
                    <li class="level0 home level-top<?php if ($routeName == 'cms' && $identifier == 'home') {
                        echo " active";
                    } ?> m-dropdown parent">
                        <a href="<?php echo $this->getBaseUrl(); ?>"
                           class="level-top"><span><?php echo $this->__('Home'); ?></span></a>
                    </li>
                <?php } ?>
                <?php
                echo $_menu;
                if (Mage::getStoreConfig('ultramegamenu/display_options/enable_custom')) {
                    $getidentifier = Mage::getStoreConfig('ultramegamenu/display_options/static_identifier');
                    $arrayidentifier = explode(";", $getidentifier);
                    foreach ($arrayidentifier as $mcustom) {
                        $static_block = explode(':', $mcustom);
                        $custom_menu = Mage::getModel('cms/block')->load($static_block[0]);
                        if ($static_block[1]) $class = 'menu-item-' . $static_block[1];
                        if ($custom_menu->getIsActive()) {
                            echo '
						<li class="level0 level-top parent custom-block ' . $class . '">
							<a href="#" class="level-top">
								<span>' . $custom_menu->getTitle() . '</span>
							</a>
							<div class="sub-wrapper">' . $this->getLayout()->createBlock('cms/block')->setBlockId($static_block[0])->toHtml() . '</div>
						</li>';
                        }
                    }
                    $urlkey = Mage::getStoreConfig('ultramegamenu/display_options/url_key');
                    $arrayUrlKey = explode(";", $urlkey);
                    foreach ($arrayUrlKey as $url) {
                        $condition = explode(':', $url);
                        $page = Mage::getModel('cms/page')->load($condition[0], 'identifier');
                        if ($condition[1]) $class = 'menu-item-' . $condition[1];
                        if ($page->getIsActive()) {
                            ?>
                            <li class="level0 level-top parent custom-block <?php if ($routeName == 'cms' && $identifier == $page->getIdentifier()) {
                                echo " active";
                            } ?> <?php echo $class; ?>">
                                <a href="<?php echo Mage::helper('cms/page')->getPageUrl($condition[0]); ?>"
                                   class="level-top">
                                    <span><?php echo $page->getTitle(); ?></span>
                                </a>
                            </li>
                        <?php
                        }
                    }
                }
                ?>
            </ul>
        </div>
    </div>
<?php endif ?>
<!-- navigation EOF -->